Traceback (most recent call last):
  File "/Users/doya/miniforge3/lib/python3.13/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
    ~~~~~~~~~^
        nb,
        ^^^
    ...<4 lines>...
        **kwargs,
        ^^^^^^^^^
    )
    ^
  File "/Users/doya/miniforge3/lib/python3.13/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/doya/miniforge3/lib/python3.13/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "/Users/doya/miniforge3/lib/python3.13/asyncio/base_events.py", line 725, in run_until_complete
    return future.result()
           ~~~~~~~~~~~~~^^
  File "/Users/doya/miniforge3/lib/python3.13/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
        cell, index, execution_count=self.code_cells_executed + 1
    )
  File "/Users/doya/miniforge3/lib/python3.13/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/doya/miniforge3/lib/python3.13/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
help()
------------------

----- stdout -----
Welcome to Python 3.13's help utility! If this is your first time using
Python, you should definitely check out the tutorial at
https://docs.python.org/3.13/tutorial/.

Enter the name of any module, keyword, or topic to get help on writing
Python programs and using Python modules.  To get a list of available
modules, keywords, symbols, or topics, enter "modules", "keywords",
"symbols", or "topics".

Each module also comes with a one-line summary of what it does; to list
the modules whose name or summary contain a given string such as "spam",
enter "modules spam".

To quit this help utility and return to the interpreter,
enter "q", "quit" or "exit".
------------------

[31m---------------------------------------------------------------------------[39m
[31mStdinNotImplementedError[39m                  Traceback (most recent call last)
[36mCell[39m[36m [39m[32mIn[90][39m[32m, line 1[39m
[32m----> [39m[32m1[39m [43mhelp[49m[43m([49m[43m)[49m

[36mFile [39m[32m<frozen _sitebuiltins>:103[39m, in [36m__call__[39m[34m(self, *args, **kwds)[39m

[36mFile [39m[32m~/miniforge3/lib/python3.13/pydoc.py:2006[39m, in [36mHelper.__call__[39m[34m(self, request)[39m
[32m   2004[39m         [38;5;28;01melse[39;00m:
[32m   2005[39m             [38;5;28mself[39m.intro()
[32m-> [39m[32m2006[39m             [38;5;28;43mself[39;49m[43m.[49m[43minteract[49m[43m([49m[43m)[49m
[32m   2007[39m             [38;5;28mself[39m.output.write([33m'''[39m
[32m   2008[39m [33mYou are now leaving help and returning to the Python interpreter.[39m
[32m   2009[39m [33mIf you want to ask for help on a particular object directly from the[39m
[32m   2010[39m [33minterpreter, you can type [39m[33m"[39m[33mhelp(object)[39m[33m"[39m[33m.  Executing [39m[33m"[39m[33mhelp([39m[33m'[39m[33mstring[39m[33m'[39m[33m)[39m[33m"[39m
[32m   2011[39m [33mhas the same effect as typing a particular string at the help> prompt.[39m
[32m   2012[39m [33m'''[39m)

[36mFile [39m[32m~/miniforge3/lib/python3.13/pydoc.py:2018[39m, in [36mHelper.interact[39m[34m(self)[39m
[32m   2016[39m [38;5;28;01mwhile[39;00m [38;5;28;01mTrue[39;00m:
[32m   2017[39m     [38;5;28;01mtry[39;00m:
[32m-> [39m[32m2018[39m         request = [38;5;28;43mself[39;49m[43m.[49m[43mgetline[49m[43m([49m[33;43m'[39;49m[33;43mhelp> [39;49m[33;43m'[39;49m[43m)[49m
[32m   2019[39m         [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m request: [38;5;28;01mbreak[39;00m
[32m   2020[39m     [38;5;28;01mexcept[39;00m ([38;5;167;01mKeyboardInterrupt[39;00m, [38;5;167;01mEOFError[39;00m):

[36mFile [39m[32m~/miniforge3/lib/python3.13/pydoc.py:2038[39m, in [36mHelper.getline[39m[34m(self, prompt)[39m
[32m   2036[39m [38;5;250m[39m[33;03m"""Read one line, using input() when appropriate."""[39;00m
[32m   2037[39m [38;5;28;01mif[39;00m [38;5;28mself[39m.input [38;5;129;01mis[39;00m sys.stdin:
[32m-> [39m[32m2038[39m     [38;5;28;01mreturn[39;00m [38;5;28;43minput[39;49m[43m([49m[43mprompt[49m[43m)[49m
[32m   2039[39m [38;5;28;01melse[39;00m:
[32m   2040[39m     [38;5;28mself[39m.output.write(prompt)

[36mFile [39m[32m~/miniforge3/lib/python3.13/site-packages/ipykernel/kernelbase.py:1281[39m, in [36mKernel.raw_input[39m[34m(self, prompt)[39m
[32m   1279[39m [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m [38;5;28mself[39m._allow_stdin:
[32m   1280[39m     msg = [33m"[39m[33mraw_input was called, but this frontend does not support input requests.[39m[33m"[39m
[32m-> [39m[32m1281[39m     [38;5;28;01mraise[39;00m StdinNotImplementedError(msg)
[32m   1282[39m [38;5;28;01mreturn[39;00m [38;5;28mself[39m._input_request(
[32m   1283[39m     [38;5;28mstr[39m(prompt),
[32m   1284[39m     [38;5;28mself[39m._parent_ident[[33m"[39m[33mshell[39m[33m"[39m],
[32m   1285[39m     [38;5;28mself[39m.get_parent([33m"[39m[33mshell[39m[33m"[39m),
[32m   1286[39m     password=[38;5;28;01mFalse[39;00m,
[32m   1287[39m )

[31mStdinNotImplementedError[39m: raw_input was called, but this frontend does not support input requests.

